// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kwyazherrsldkdfptojo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt3eWF6aGVycnNsZGtkZnB0b2pvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzM1NjM4MjUsImV4cCI6MjA4OTEzOTgyNX0.Id-gEiaYJgq_cy8wxfkTB1NgGwuS818QmnFyzMJtQSw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});